title: My Portfolio
author: Your Name
description: Full-stack developer portfolio specializing in Ruby on Rails backend development and front-end work with Angular, JavaScript, CSS, and Bootstrap.
theme: jekyll-theme-minimal
